---
abstract: 'Page Navigator plugin for Mojolicious'
author:
  - 'dokechin <>'
build_requires:
  Test::Mojo: 0
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.6.7, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-BootstrapPagination
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Mojolicious::Plugin::BootstrapPagination:
    file: lib/Mojolicious/Plugin/BootstrapPagination.pm
    version: 0.11
requires:
  Mojolicious: 4.0
  perl: 5.008001
resources:
  bugtracker: https://github.com/dokechin/Mojolicious-Plugin-BootstrapPagination/issues
  homepage: https://github.com/dokechin/Mojolicious-Plugin-BootstrapPagination
  repository: https://github.com/dokechin/Mojolicious-Plugin-BootstrapPagination.git
version: 0.11
x_contributors:
  - 'dokechin <user@user-PC.(none)>'
  - 'Andrey Kuzmin <chips@reg.ru>'
  - 'dokechin <ttatsumi@ra2.so-net.ne.jp>'
